[project]
name = "clivet-integration"
version = "0.1.0"
description = "Integration for Home Assistant for Clivet Sphera-T heat pumps"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pymodbus>=3.9.2"]

[dependency-groups]
dev = [
    "ruff>=0.12.9",
]
