name: Validate

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  validate-ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v6
      
      - name: Ruff format check
        run: |
          uv run ruff format --check --config pyproject.toml custom_components/clivet
      
      - name: Ruff check
        run: |
          uv run ruff check --config pyproject.toml custom_components/clivet